import { Octokit } from 'octokit'

function octokit() { return new Octokit({ auth: process.env.GITHUB_TOKEN }) }
const GITHUB_USERNAME = process.env.GITHUB_USERNAME || 'Crapes18'

export async function createRepo(slug, description) {
  try {
    // Check if repo already exists
    const existing = await octokit().rest.repos.get({
      owner: GITHUB_USERNAME,
      repo: slug,
    }).catch(() => null)

    if (existing) return existing.data

    const { data } = await octokit().rest.repos.createForAuthenticatedUser({
      name: slug,
      description,
      private: false,
      auto_init: true,
    })
    // Wait for GitHub to initialize the repo
    await new Promise(r => setTimeout(r, 2000))
    return data
  } catch (err) {
    console.error('[github] createRepo error:', err.message)
    throw err
  }
}

export async function pushFiles(slug, files) {
  // Get the latest commit SHA on main
  const { data: ref } = await octokit().rest.git.getRef({
    owner: GITHUB_USERNAME,
    repo: slug,
    ref: 'heads/main',
  })
  const baseSha = ref.object.sha

  // Get the tree SHA
  const { data: commit } = await octokit().rest.git.getCommit({
    owner: GITHUB_USERNAME,
    repo: slug,
    commit_sha: baseSha,
  })
  const baseTreeSha = commit.tree.sha

  // Create blobs for all files
  const treeItems = await Promise.all(
    files.map(async ({ path, content }) => {
      const { data: blob } = await octokit().rest.git.createBlob({
        owner: GITHUB_USERNAME,
        repo: slug,
        content: Buffer.from(content).toString('base64'),
        encoding: 'base64',
      })
      return { path, mode: '100644', type: 'blob', sha: blob.sha }
    })
  )

  // Create new tree
  const { data: newTree } = await octokit().rest.git.createTree({
    owner: GITHUB_USERNAME,
    repo: slug,
    base_tree: baseTreeSha,
    tree: treeItems,
  })

  // Create commit
  const { data: newCommit } = await octokit().rest.git.createCommit({
    owner: GITHUB_USERNAME,
    repo: slug,
    message: 'feat: initial prototype generated by Idea Engine',
    tree: newTree.sha,
    parents: [baseSha],
  })

  // Update ref
  await octokit().rest.git.updateRef({
    owner: GITHUB_USERNAME,
    repo: slug,
    ref: 'heads/main',
    sha: newCommit.sha,
  })

  return `https://github.com/${GITHUB_USERNAME}/${slug}`
}

export function repoUrl(slug) {
  return `https://github.com/${GITHUB_USERNAME}/${slug}`
}

export async function enableGitHubPages(slug) {
  try {
    await octokit().rest.repos.createPagesSite({
      owner: GITHUB_USERNAME,
      repo: slug,
      source: { branch: 'main', path: '/' },
    })
  } catch (e) {
    // Already enabled or other non-fatal error
    if (!e.message?.includes('already')) console.warn('[github] pages enable:', e.message)
  }
  // Wait for Pages to provision
  await new Promise(r => setTimeout(r, 8000))
  return `https://${GITHUB_USERNAME.toLowerCase()}.github.io/${slug}`
}

export async function readFile(repo, path) {
  const { data } = await octokit().rest.repos.getContent({
    owner: GITHUB_USERNAME,
    repo,
    path,
  })
  const content = Buffer.from(data.content, 'base64').toString('utf-8')
  return { content, sha: data.sha }
}

export async function updateFile(repo, path, content, sha, message) {
  await octokit().rest.repos.createOrUpdateFileContents({
    owner: GITHUB_USERNAME,
    repo,
    path,
    message,
    content: Buffer.from(content).toString('base64'),
    sha,
  })
}
